---
title: My first Blog
author: Bhavna Jain
email: jainbhavna4545@gmail.com
theme: minima
---
description: > # this means to ignore newlines until "baseurl:"
  Hey, I am Bhavna Jain. I am currently pursuing B.tech final year in IT from Banashali Vidyapith Jaipur. 
  My Hobbies are Reading, writing, Drama.
  I am a ISDL intern in IBM.
  I am a upcoming Software engineer at Optum.
  I live in Mathura which is a very holistic place.
  I am strong determined to change my inner and outer world trough my actions and keep hustling for that.
  I love myself.
  

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: bhavna-jain409

